export default {
  SET_LOGIN: 'SET_LOGIN',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_CASE_LIST: 'SET_CASE_LIST',
  SET_CASE_ID: 'SET_CASE_ID',
  SET_CASE_NO: 'SET_CASE_NO',
  SET_ROOM_TOKEN: 'SET_ROOM_TOKEN',
  SET_USERID: 'SET_USERID',
  SET_MESSAGE: 'SET_MESSAGE',
  SET_EVI_LIST: 'SET_EVI_LIST',
  SET_EVI_LIST_FORMAT: 'SET_EVI_LIST_FORMAT',
  SET_VIDEO_SRC_OBJ: 'SET_VIDEO_SRC_OBJ',
  SET_WEBSOCKET: 'SET_WEBSOCKET',
  SET_MAININFO: 'SET_MAININFO'
}
